######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 27 15:40:22 2011
######################################################################

TEMPLATE = app
TARGET = 

include(../api/api.pri)

QMAKE_RPATHDIR = ../api/lib
# Input
SOURCES += main.cpp
