#ifndef SUBSERVERAPI_GLOBAL_H
#define SUBSERVERAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SUBSERVERAPI_LIBRARY)
#  define SUBSERVERAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SUBSERVERAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SUBSERVERAPI_GLOBAL_H
