######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 20 18:37:45 2011
######################################################################

QT += network
TEMPLATE = lib
TARGET = 
DEPENDPATH += . src/network
INCLUDEPATH += . src/network

# Input
HEADERS += src/network/jnetworkdataprocessorbase.h src/network/jsocketbase.h \
    src/global/jglobal.h
SOURCES += src/network/jsocketbase.cpp
